global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: arbiter-scheduler
    metrics_path: /metrics
    static_configs:
      - targets:
          - scheduler:8080
          - scheduler-2:8080
          - scheduler-3:8080
        labels:
          component: scheduler

  - job_name: arbiter-worker
    metrics_path: /metrics
    static_configs:
      - targets:
          - worker:8081
          - worker-2:8082
          - worker-3:8083
          - worker-4:8084
          - worker-5:8085
        labels:
          component: worker
